quarkus:
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:file:./data/db;AUTO_SERVER=TRUE
  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
